### ISSUE TITLE
Repo updates for GHEC

### ISSUE THREAD

**Issue by smwoodman** [SWFSC/glider-lab#28]
@acossio no rush here, just starting this issue to keep track of steps that need to happen before moving this repo to Enterprise

- [x] Change repo name. Current thought is 'glider-lab' to mirror https://github.com/SWFSC/glider-lab-manual
- [x] Update repo license to CC1.0 since this isn't a code repo. Based on https://nmfs-opensci.github.io/GitHub-Guide/#sec-license (SMW will do)
- [x] Update disclaimer formatting (SMW will do)
- [x] Decide on repo being public/internal. If internal, then we'll have to do additional secret scanning things as described in the 'Required elements for repositories in SWFSC' section of the SWFSC SOP (link on [this Sites page](https://sites.google.com/noaa.gov/inside-swfsc/home/technology/github))

**Comment by acossio** [comment]
@smwoodman I changed the name. I'm also fine with making it public so Heidi can look at it without creating an account. I changed it to public so hopefully we can add multiple people to an issue. 
If you agree to all the changes, go ahead and close the issue.

**Comment by acossio** [comment]
Because it is now a public repo, we can assign multiple people to an issue.

**Comment by acossio** [comment]
changed to glider-lab.
I think we will also need to make the project public for people like Heidi to see it. I'll test that later today.

**Comment by smwoodman** [comment]
Thanks Tony! Closing this issue now
